#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts /tmp/hosts_tmp

sed 's/127\.0\.0\.1\([[:space:]]*\)localhost/127.0.0.2\1localhost/' /tmp/hosts_tmp > /tmp/hosts_new

if grep -q 'facebook\.com' /tmp/hosts_new; then
    sed -i 's/.*facebook\.com.*/8.8.8.8 facebook.com/' /tmp/hosts_new
else
    echo "8.8.8.8 facebook.com" >> /tmp/hosts_new
fi

cp /tmp/hosts_new /etc/hosts
rm -f /tmp/hosts_tmp /tmp/hosts_new
